/*
 * This file is generated by jOOQ.
 */
package com.jagt.employ.user.infra.model;


import com.jagt.employ.user.infra.model.tables.Hello;
import com.jagt.employ.user.infra.model.tables.UA;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployBiz extends SchemaImpl {

    private static final long serialVersionUID = -1350575536;

    /**
     * The reference instance of <code>employ-biz</code>
     */
    public static final EmployBiz EMPLOY_BIZ = new EmployBiz();

    /**
     * The table <code>employ-biz.hello</code>.
     */
    public final Hello HELLO = com.jagt.employ.user.infra.model.tables.Hello.HELLO;

    /**
     * The table <code>employ-biz.u_a</code>.
     */
    public final UA U_A = com.jagt.employ.user.infra.model.tables.UA.U_A;

    /**
     * No further instances allowed
     */
    private EmployBiz() {
        super("employ-biz", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Hello.HELLO,
            UA.U_A);
    }
}
