/*
 * This file is generated by jOOQ.
 */
package com.jagt.employ.user.infra.model;


import com.jagt.employ.user.infra.model.tables.Hello;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>employ-biz</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HELLO_PRIMARY = Indexes0.HELLO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index HELLO_PRIMARY = Internal.createIndex("PRIMARY", Hello.HELLO, new OrderField[] { Hello.HELLO.ID }, true);
    }
}
