/*
 * This file is generated by jOOQ.
 */
package com.jagt.employ.student.infra.model;


import com.jagt.employ.student.infra.model.tables.Hello;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>employ-biz</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Long> IDENTITY_HELLO = Identities0.IDENTITY_HELLO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> KEY_HELLO_PRIMARY = UniqueKeys0.KEY_HELLO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<Record, Long> IDENTITY_HELLO = Internal.createIdentity(Hello.HELLO, Hello.HELLO.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> KEY_HELLO_PRIMARY = Internal.createUniqueKey(Hello.HELLO, "KEY_hello_PRIMARY", Hello.HELLO.ID);
    }
}
