/*
 * This file is generated by jOOQ.
 */
package com.jagt.employ.student.infra.model;


import com.jagt.employ.student.infra.model.tables.Hello;
import com.jagt.employ.student.infra.model.tables.UA;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in employ-biz
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>employ-biz.hello</code>.
     */
    public static final Hello HELLO = com.jagt.employ.student.infra.model.tables.Hello.HELLO;

    /**
     * The table <code>employ-biz.u_a</code>.
     */
    public static final UA U_A = com.jagt.employ.student.infra.model.tables.UA.U_A;
}
